/* Cloudflare entry point for the storefront.
 *
 * Three jobs, and the order matters:
 *
 *   /api/*, /uploads/*   ->  forwarded to the Express API, wherever it runs
 *   /robots.txt, /sitemap.xml  ->  generated by the API, served from the root
 *   HTML documents        ->  the built React app, with its <head> filled in
 *   everything else       ->  the built React app out of ./dist, untouched
 *
 * The forwarding is the original point. The client fetches relative paths --
 * see `fetch(`/api${path}`)` in src/lib/api.js -- which means "the same site I
 * was served from". Keeping that true is what lets the API live on a different
 * machine without touching a line of client code and without the browser
 * treating it as a cross-origin request, which would drag in CORS preflights
 * and cookie rules for no benefit.
 *
 * `run_worker_first` in wrangler.jsonc lists exactly the prefixes this handles,
 * so it runs before the asset router for them and not at all for anything else.
 * Without it the SPA fallback would answer /api/products with index.html --
 * every path matches an asset once not_found_handling is
 * single-page-application, so the Worker would never see the request.
 */

const API_PREFIXES = ['/api/', '/uploads/'];

/* Never rewritten: the admin is behind a login and has nothing to say to a
   crawler, and rewriting it would only add latency to the one part of the site
   whose users are already signed in. */
const NO_SEO = ['/admin'];

const jsonEscape = (s) => String(s ?? '').replace(/</g, '&lt;').replace(/"/g, '&quot;');

/**
 * Asks the API what a URL is about.
 *
 * Cached at the edge for the same five minutes the API's own Cache-Control
 * asks for, because a crawl is thousands of requests in a few minutes and the
 * API is on a free tier that would feel every one of them. `cacheEverything`
 * is required: without it Cloudflare will not cache a subrequest response it
 * considers dynamic, and the header alone is not enough.
 */
async function fetchSeo(origin, path) {
  const target = `${origin}/api/seo/page?path=${encodeURIComponent(path)}`;
  const res = await fetch(target, {
    cf: { cacheEverything: true, cacheTtl: 300 },
  });
  if (!res.ok) return null;
  return res.json();
}

/**
 * Splices the metadata into the shell.
 *
 * HTMLRewriter streams, so this costs a few milliseconds and no buffering --
 * which is why it can run on every page view rather than only for crawlers.
 * Doing it for everyone also means what a crawler sees is exactly what a person
 * sees, which is the line between filling in a template and cloaking.
 */
function rewrite(response, seo) {
  return new HTMLRewriter()
    /* The shell ships a static title so a hard-refresh is never blank. Replace
       its text rather than appending a second <title>, which browsers and
       crawlers resolve inconsistently. */
    .on('title', {
      element(el) { el.setInnerContent(seo.title); },
    })
    /* The shell ships fallback metadata so the page is still shareable if this
       Worker is misconfigured or the API is down. When it is working, those
       fallbacks have to go before the real ones are appended: every consumer
       here takes the FIRST tag it finds, and the shell's tags come first in
       document order, so appending without removing would mean the real title
       and description were never read. */
    .on('meta[name="description"], meta[name="robots"], meta[property^="og:"], meta[name^="twitter:"], link[rel="canonical"]', {
      element(el) { el.remove(); },
    })
    .on('head', {
      element(el) { el.append(`\n    ${seo.head}\n  `, { html: true }); },
    })
    /* The crawlable copy goes inside #root. React's createRoot replaces the
       children of that div on its first render, so a visitor never sees this --
       it is there for the crawlers that read the HTML and stop, which is most
       of the ones that feed AI answers. It is generated from the same database
       rows the components render, so it cannot drift from the real page. */
    .on('#root', {
      element(el) {
        /* Wrapped in a hidden element rather than poured straight in. The
           browser paints this summary the moment it arrives, and React only
           replaces it once the bundle has parsed -- so every visitor met a
           flash of unstyled headings and links first. On an ad click, that
           flash is the first impression the money bought.
           `hidden` costs a crawler nothing: the markup is still there to
           parse, and one that does run the bundle sees the same content
           rendered properly. */
        if (seo.body) el.setInnerContent(`<div data-prerender hidden>${seo.body}</div>`, { html: true });
      },
    })
    .transform(response);
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    const apiMissing = () =>
      Response.json({ error: 'API_ORIGIN is not configured on this Worker.' }, { status: 503 });

    /* ---- the API proxy ---- */
    if (API_PREFIXES.some((prefix) => url.pathname.startsWith(prefix))) {
      if (!env.API_ORIGIN) return apiMissing();

      const target = new URL(url.pathname + url.search, env.API_ORIGIN);

      /* `new Request(target, request)` carries the method, headers and body
         across unchanged. That matters for three routes in particular: the
         Razorpay webhook is signed over the exact bytes of its body, and
         /api/upload and /api/reviews/video send multipart form data. Re-reading
         or re-serialising any of them would break it.
         `redirect: 'manual'` so a redirect from the API is handed back to the
         browser as-is instead of being chased from inside the Worker, which
         would lose the original URL. */
      return fetch(new Request(target, request), { redirect: 'manual' });
    }

    /* ---- robots.txt and sitemap.xml ----
       Both have to answer at the root of the site: a crawler looks for
       /robots.txt and nowhere else, and a sitemap is only trusted for URLs
       under the path it is served from. They are generated by the API because
       the sitemap has to list the current catalogue, which only the database
       knows. Cached hard -- a sitemap that regenerates on every hit is a
       denial-of-service someone else runs for you. */
    if (url.pathname === '/robots.txt' || url.pathname === '/sitemap.xml') {
      if (!env.API_ORIGIN) return apiMissing();
      const name = url.pathname === '/robots.txt' ? 'robots.txt' : 'sitemap.xml';
      return fetch(`${env.API_ORIGIN}/api/seo/${name}`, {
        cf: { cacheEverything: true, cacheTtl: 3600 },
      });
    }

    /* ---- everything else comes from the built app ---- */
    const assetResponse = await env.ASSETS.fetch(request);

    /* Only HTML documents are candidates for rewriting. An asset request that
       fell through to the SPA fallback, a HEAD, a POST, or a response that is
       not HTML is handed back exactly as it came. */
    const isDocument = request.method === 'GET'
      && (assetResponse.headers.get('content-type') || '').includes('text/html')
      && !NO_SEO.some((p) => url.pathname === p || url.pathname.startsWith(`${p}/`));

    if (!isDocument || !env.API_ORIGIN) return assetResponse;

    let seo = null;
    try {
      seo = await fetchSeo(env.API_ORIGIN, url.pathname);
    } catch {
      /* The API is down, restarting, or slow. Serving the un-rewritten shell is
         the right failure: the site still works for people, and a crawler gets
         the static title rather than a 502. */
      return assetResponse;
    }
    if (!seo?.title) return assetResponse;

    const out = rewrite(assetResponse, seo);

    /* The shell is identical for every URL, so without this the CDN would hand
       the /shop rewrite to someone asking for /product/x. Vary on nothing and
       cache per-URL: the response now genuinely differs by path. */
    const headers = new Headers(out.headers);
    headers.set('Cache-Control', 'public, max-age=0, s-maxage=300, stale-while-revalidate=3600');
    headers.set('X-Robots-Tag', jsonEscape(seo.robots || 'index, follow'));

    return new Response(out.body, { status: out.status, headers });
  },
};
